version: "3.9"
services:
  dyu_fr_inference_util:
    container_name: dyu_fr_inference_util
    image: local/dyu-fr-inference-joeynmt-v27.0:latest
    command: --model_name=model
    working_dir: /app
    ports:
      - "8080:8080"